- name: Install system tools
  hosts: all
  become: true
  tasks:

  - name: Install nvim
    ansible.builtin.apt:
      name:
        - neovim
      update_cache: true
      state: present

  - name: Upgrade packages
    ansible.builtin.apt:
      upgrade: full
