local assert = require('luassert')
local describe = require('plenary.busted').describe
local it = require('plenary.busted').it
local stub = require('luassert.stub')

describe('md_actions', function()
    local md_actions

    before_each(function()
        md_actions = require('config.md_actions')
    end)

    describe('format_link', function()
        it('formats text and url into markdown link', function()
            assert.are.equal('[hello](https://example.com)', md_actions.format_link('hello', 'https://example.com'))
            assert.are.equal('[](url)', md_actions.format_link('', 'url'))
            assert.are.equal('[text with spaces](url with spaces)',
                md_actions.format_link('text with spaces', 'url with spaces'))
        end)
    end)

    describe('is_visual_mode_supported', function()
        it('returns true for character and line visual modes', function()
            assert.is_true(md_actions.is_visual_mode_supported('v'))
            assert.is_true(md_actions.is_visual_mode_supported('V'))
        end)

        it('returns false for blockwise visual mode', function()
            assert.is_false(md_actions.is_visual_mode_supported('\022'))
        end)
    end)

    describe('normalize_positions', function()
        it('returns positions as is if start before end', function()
            local srow, scol, erow, ecol = md_actions.normalize_positions(1, 1, 2, 1)
            assert.are.equal(1, srow)
            assert.are.equal(1, scol)
            assert.are.equal(2, erow)
            assert.are.equal(1, ecol)
        end)

        it('swaps positions if start after end', function()
            local srow, scol, erow, ecol = md_actions.normalize_positions(2, 1, 1, 1)
            assert.are.equal(1, srow)
            assert.are.equal(1, scol)
            assert.are.equal(2, erow)
            assert.are.equal(1, ecol)
        end)

        it('swaps positions if same row but start col after end col', function()
            local srow, scol, erow, ecol = md_actions.normalize_positions(1, 3, 1, 1)
            assert.are.equal(1, srow)
            assert.are.equal(1, scol)
            assert.are.equal(1, erow)
            assert.are.equal(3, ecol)
        end)
    end)

    describe('convert_to_api_indices', function()
        it('converts for character visual mode', function()
            local start_row, start_col, end_row, end_col_excl = md_actions.convert_to_api_indices('v', 1, 1, 1, 3)
            assert.are.equal(0, start_row)
            assert.are.equal(0, start_col)
            assert.are.equal(0, end_row)
            assert.are.equal(3, end_col_excl)
        end)

        it('converts for line visual mode', function()
            stub(vim.fn, 'col')
            vim.fn.col.returns(10)
            local start_row, start_col, end_row, end_col_excl = md_actions.convert_to_api_indices('V', 1, 1, 2, 1)
            assert.are.equal(0, start_row)
            assert.are.equal(0, start_col)
            assert.are.equal(1, end_row)
            assert.are.equal(9, end_col_excl)  -- 10 - 1
            vim.fn.col:revert()
        end)
    end)

    describe('get_url_from_clipboard', function()
        it('gets URL from clipboard and trims trailing spaces', function()
            stub(vim.fn, 'getreg')
            vim.fn.getreg.returns('https://example.com   ')
            local url = md_actions.get_url_from_clipboard()
            assert.are.equal('https://example.com', url)
            vim.fn.getreg:revert()
        end)

        it('returns empty string if clipboard empty', function()
            stub(vim.fn, 'getreg')
            vim.fn.getreg.returns('')
            local url = md_actions.get_url_from_clipboard()
            assert.are.equal('', url)
            vim.fn.getreg:revert()
        end)
    end)

    describe('get_visual_positions', function()
        it('gets visual and cursor positions', function()
            stub(vim.fn, 'getpos')
            vim.fn.getpos.on_call_with('v').returns({0, 1, 2, 0})
            vim.fn.getpos.on_call_with('.').returns({0, 1, 4, 0})
            local srow, scol, erow, ecol = md_actions.get_visual_positions()
            assert.are.equal(1, srow)
            assert.are.equal(2, scol)
            assert.are.equal(1, erow)
            assert.are.equal(4, ecol)
            vim.fn.getpos:revert()
        end)
    end)

    describe('get_selected_text', function()
        it('gets text from buffer', function()
            stub(vim.api, 'nvim_buf_get_text')
            vim.api.nvim_buf_get_text.returns({'hello', 'world'})
            local text = md_actions.get_selected_text(0, 0, 0, 1, 5)
            assert.are.equal('hello\nworld', text)
            vim.api.nvim_buf_get_text:revert()
        end)
    end)

    describe('replace_selection', function()
        it('replaces text in buffer', function()
            stub(vim.api, 'nvim_buf_set_text')
            md_actions.replace_selection(0, 0, 0, 1, 5, 'replacement')
            assert.stub(vim.api.nvim_buf_set_text).was_called_with(0, 0, 0, 1, 5, {'replacement'})
            vim.api.nvim_buf_set_text:revert()
        end)
    end)

    describe('exit_visual_mode', function()
        it('exits visual mode by feeding Esc', function()
            stub(vim.api, 'nvim_feedkeys')
            stub(vim.api, 'nvim_replace_termcodes')
            vim.api.nvim_replace_termcodes.returns('\27')
            md_actions.exit_visual_mode()
            assert.stub(vim.api.nvim_feedkeys).was_called_with('\27', 'n', true)
            vim.api.nvim_feedkeys:revert()
            vim.api.nvim_replace_termcodes:revert()
        end)
    end)

    describe('wrap_visual_selection_as_md_link', function()
        it('wraps selection as markdown link', function()
            -- Mock all dependencies
            stub(md_actions, 'get_url_from_clipboard').returns('https://example.com')
            stub(vim.fn, 'visualmode').returns('v')
            stub(md_actions, 'is_visual_mode_supported').returns(true)
            stub(md_actions, 'get_visual_positions').returns(1, 1, 1, 5)
            stub(md_actions, 'normalize_positions').returns(1, 1, 1, 5)
            stub(md_actions, 'convert_to_api_indices').returns(0, 0, 0, 5)
            stub(md_actions, 'get_selected_text').returns('hello')
            stub(md_actions, 'format_link').returns('[hello](https://example.com)')
            stub(md_actions, 'replace_selection')
            stub(md_actions, 'exit_visual_mode')

            md_actions.wrap_visual_selection_as_md_link()

            assert.stub(md_actions.get_url_from_clipboard).was_called()
            assert.stub(vim.fn.visualmode).was_called()
            assert.stub(md_actions.is_visual_mode_supported).was_called_with('v')
            assert.stub(md_actions.get_visual_positions).was_called()
            assert.stub(md_actions.normalize_positions).was_called_with(1, 1, 1, 5)
            assert.stub(md_actions.convert_to_api_indices).was_called_with('v', 1, 1, 1, 5)
            assert.stub(md_actions.get_selected_text).was_called_with(0, 0, 0, 0, 5)
            assert.stub(md_actions.format_link).was_called_with('hello', 'https://example.com')
            assert.stub(md_actions.replace_selection).was_called_with(0, 0, 0, 0, 5, '[hello](https://example.com)')
            assert.stub(md_actions.exit_visual_mode).was_called()

            -- Revert all stubs
            md_actions.get_url_from_clipboard:revert()
            vim.fn.visualmode:revert()
            md_actions.is_visual_mode_supported:revert()
            md_actions.get_visual_positions:revert()
            md_actions.normalize_positions:revert()
            md_actions.convert_to_api_indices:revert()
            md_actions.get_selected_text:revert()
            md_actions.format_link:revert()
            md_actions.replace_selection:revert()
            md_actions.exit_visual_mode:revert()
        end)

        it('warns if clipboard is empty', function()
            stub(md_actions, 'get_url_from_clipboard').returns('')
            stub(vim, 'notify')

            md_actions.wrap_visual_selection_as_md_link()

            assert.stub(vim.notify).was_called_with("Clipboard (+ register) is empty. Copy a URL first.", vim.log.levels.WARN)

            md_actions.get_url_from_clipboard:revert()
            vim.notify:revert()
        end)

        it('warns if visual mode not supported', function()
            stub(md_actions, 'get_url_from_clipboard').returns('url')
            stub(vim.fn, 'visualmode').returns('\022')
            stub(md_actions, 'is_visual_mode_supported').returns(false)
            stub(vim, 'notify')

            md_actions.wrap_visual_selection_as_md_link()

            assert.stub(vim.notify).was_called_with("Blockwise visual mode not supported by this snippet.", vim.log.levels.WARN)

            md_actions.get_url_from_clipboard:revert()
            vim.fn.visualmode:revert()
            md_actions.is_visual_mode_supported:revert()
            vim.notify:revert()
        end)
    end)

    describe('is_url', function()
        it('returns true for http urls', function()
            assert.is_true(md_actions.is_url('http://example.com'))
            assert.is_true(md_actions.is_url('https://example.com'))
        end)

        it('returns false for non-url strings', function()
            assert.is_false(md_actions.is_url('hello world'))
            assert.is_false(md_actions.is_url('ftp://example.com'))
            assert.is_false(md_actions.is_url(''))
        end)
    end)

    describe('is_jira_url', function()
        it('returns true for jira urls', function()
            assert.is_true(md_actions.is_jira_url('https://company.atlassian.net/browse/PROJ-123'))
            assert.is_true(md_actions.is_jira_url('https://jira.example.com/browse/TICKET-456'))
        end)

        it('returns false for non-jira urls', function()
            assert.is_false(md_actions.is_jira_url('https://example.com'))
            assert.is_false(md_actions.is_jira_url('https://notion.so/page'))
            assert.is_false(md_actions.is_jira_url('https://www.google.com/search?q=jira'))
        end)
    end)

    describe('extract_jira_ticket', function()
        it('extracts ticket from jira url', function()
            assert.are.equal('PROJ-123', md_actions.extract_jira_ticket('https://company.atlassian.net/browse/PROJ-123'))
            assert.are.equal('TICKET-456', md_actions.extract_jira_ticket('https://jira.example.com/browse/TICKET-456?param=value'))
        end)
    end)

    describe('is_notion_url', function()
        it('returns true for notion urls', function()
            assert.is_true(md_actions.is_notion_url('https://www.notion.so/Page-Title-1234567890abcdef'))
            assert.is_true(md_actions.is_notion_url('https://notion.so/workspace/Page-456'))
        end)

        it('returns false for non-notion urls', function()
            assert.is_false(md_actions.is_notion_url('https://example.com'))
            assert.is_false(md_actions.is_notion_url('https://jira.atlassian.net'))
        end)
    end)

    describe('get_notion_title', function()
        it('extracts title from notion url', function()
            local title = md_actions.get_notion_title('https://www.notion.so/workspace/My-Page-Title-1234567890abcdef')
            assert.are.equal('My Page Title', title)
        end)

        it('returns default if no path', function()
            local title = md_actions.get_notion_title('https://notion.so')
            assert.are.equal('Notion Page', title)
        end)
    end)

    describe('extract_domain', function()
        it('extracts domain from url', function()
            assert.are.equal('example.com', md_actions.extract_domain('https://example.com/path'))
            assert.are.equal('sub.example.com', md_actions.extract_domain('https://sub.example.com'))
            assert.are.equal('example.co.uk', md_actions.extract_domain('http://example.co.uk/test'))
        end)
    end)

    describe('paste_md_link_from_clipboard', function()
        it('pastes jira link', function()
            stub(md_actions, 'get_url_from_clipboard').returns('https://company.atlassian.net/browse/PROJ-123')
            stub(md_actions, 'is_url').returns(true)
            stub(md_actions, 'is_jira_url').returns(true)
            stub(md_actions, 'extract_jira_ticket').returns('PROJ-123')
            stub(md_actions, 'format_link').returns('[PROJ-123](https://company.atlassian.net/browse/PROJ-123)')
            stub(vim.api, 'nvim_win_get_cursor').returns({1, 0})
            stub(vim.api, 'nvim_buf_set_text')

            md_actions.paste_md_link_from_clipboard()

            assert.stub(vim.api.nvim_buf_set_text).was_called_with(0, 0, 0, 0, 0, {'[PROJ-123](https://company.atlassian.net/browse/PROJ-123)'})

            md_actions.get_url_from_clipboard:revert()
            md_actions.is_url:revert()
            md_actions.is_jira_url:revert()
            md_actions.extract_jira_ticket:revert()
            md_actions.format_link:revert()
            vim.api.nvim_win_get_cursor:revert()
            vim.api.nvim_buf_set_text:revert()
        end)

        it('pastes notion link', function()
            stub(md_actions, 'get_url_from_clipboard').returns('https://notion.so/Page-123')
            stub(md_actions, 'is_url').returns(true)
            stub(md_actions, 'is_jira_url').returns(false)
            stub(md_actions, 'is_notion_url').returns(true)
            stub(md_actions, 'get_notion_title').returns('Page Title')
            stub(md_actions, 'format_link').returns('[Page Title](https://notion.so/Page-123)')
            stub(vim.api, 'nvim_win_get_cursor').returns({2, 5})
            stub(vim.api, 'nvim_buf_set_text')

            md_actions.paste_md_link_from_clipboard()

            assert.stub(vim.api.nvim_buf_set_text).was_called_with(0, 1, 5, 1, 5, {'[Page Title](https://notion.so/Page-123)'})

            md_actions.get_url_from_clipboard:revert()
            md_actions.is_url:revert()
            md_actions.is_jira_url:revert()
            md_actions.is_notion_url:revert()
            md_actions.get_notion_title:revert()
            md_actions.format_link:revert()
            vim.api.nvim_win_get_cursor:revert()
            vim.api.nvim_buf_set_text:revert()
        end)

        it('pastes domain link for other urls', function()
            stub(md_actions, 'get_url_from_clipboard').returns('https://example.com/article')
            stub(md_actions, 'is_url').returns(true)
            stub(md_actions, 'is_jira_url').returns(false)
            stub(md_actions, 'is_notion_url').returns(false)
            stub(md_actions, 'extract_domain').returns('example.com')
            stub(md_actions, 'format_link').returns('[example.com](https://example.com/article)')
            stub(vim.api, 'nvim_win_get_cursor').returns({1, 10})
            stub(vim.api, 'nvim_buf_set_text')

            md_actions.paste_md_link_from_clipboard()

            assert.stub(vim.api.nvim_buf_set_text).was_called_with(0, 0, 10, 0, 10, {'[example.com](https://example.com/article)'})

            md_actions.get_url_from_clipboard:revert()
            md_actions.is_url:revert()
            md_actions.is_jira_url:revert()
            md_actions.is_notion_url:revert()
            md_actions.extract_domain:revert()
            md_actions.format_link:revert()
            vim.api.nvim_win_get_cursor:revert()
            vim.api.nvim_buf_set_text:revert()
        end)

        it('does nothing if clipboard is not a url', function()
            stub(md_actions, 'get_url_from_clipboard').returns('not a url')
            stub(md_actions, 'is_url').returns(false)
            stub(vim.api, 'nvim_win_get_cursor')
            stub(vim.api, 'nvim_buf_set_text')

            md_actions.paste_md_link_from_clipboard()

            assert.stub(vim.api.nvim_win_get_cursor).was_not_called()
            assert.stub(vim.api.nvim_buf_set_text).was_not_called()

            md_actions.get_url_from_clipboard:revert()
            md_actions.is_url:revert()
            vim.api.nvim_win_get_cursor:revert()
            vim.api.nvim_buf_set_text:revert()
        end)
    end)
end)
