-- TODOs:
-- * treesitter, all the parsers
-- * treesitter-textobjects
-- * treesitter-context
-- * neotest
-- * copilot
-- * cmp
-- * lsp-progress
-- * early retirement
-- * diff view
-- * git conflict
-- * indent blankline
-- * iron
return {}
