# Source:
# * https://support.1password.com/install-linux/
# * https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html#examples
- name: Add 1Password Yum Repo
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
  become: true
  tags: superuser

- name: Install 1Password
  ansible.builtin.dnf:
    name:
      - 1password
    state: present
  become: true
  tags: superuser
