- name: add docker-ce DNF repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "644"
  become: true
  tags: superuser

# Check out https://docs.docker.com/desktop/install/fedora/ to get the latest
# RPM package link.

- name: install docker desktop
  ansible.builtin.dnf:
    name: https://desktop.docker.com/linux/main/amd64/docker-desktop-4.26.1-x86_64.rpm
    state: present
    # The official Docker Desktop guide doesn't show how to validate GPG.
    disable_gpg_check: true
  become: true
  tags: superuser

