- name: Set up Go
  hosts: all
  tasks:

  - name: Install golang
    ansible.builtin.dnf:
      name: golang
      state: present
    become: true

  - name: Create GOPATH directory
    ansible.builtin.file:
      path: /home/alex/.local/share/aj-apps/golang
      state: directory
    become_user: alex
    become: true
