- name: Clone and link dotfiles
  hosts: all
  tasks:

  - name: clone dotfiles
    git:
      repo: git@github.com:alexjuda/dotfiles.git
      dest: ~/Code/dotfiles
      clone: yes
      update: no

  - name: link kitty config
    ansible.builtin.file:
      src: ~/Code/dotfiles/config/kitty
      dest: ~/.config/kitty
      state: link

  - name: link wezterm config
    ansible.builtin.file:
      src: ~/Code/dotfiles/config/wezterm
      dest: ~/.config/wezterm
      state: link

  - name: link neovim config
    ansible.builtin.file:
      src: ~/Code/dotfiles/config/nvim
      dest: ~/.config/nvim
      state: link

  - name: make ghostty config dir
    ansible.builtin.file:
      path: ~/.config/ghostty
      state: directory

  - name: link main ghostty config
    ansible.builtin.file:
      src: ~/Code/dotfiles/config/ghostty/config
      dest: ~/.config/ghostty/config
      state: link

  - name: link platform-specific ghostty config
    ansible.builtin.file:
      src: ~/Code/dotfiles/config/ghostty/linux_config
      dest: ~/.config/ghostty/platform_specific_config
      state: link

  # There's a bunch of other crap opencode creates and keeps under '~/.config/opencode/' dir. We just need to link the
  # config file. I wish they made proper use of XDG confgi and state dirs.
  - name: link opencode config file
    ansible.builtin.file:
      src: ~/Code/dotfiles/config/opencode/opencode.json
      dest: ~/.config/opencode/opencode.json
      state: link

  - name: link zsh config
    ansible.builtin.file:
      src: ~/Code/dotfiles/macos/.zshrc
      dest: ~/.zshrc
      state: link

  - name: link aliases
    ansible.builtin.file:
      src: ~/Code/dotfiles/linux/.bash_aliases
      dest: ~/.bash_aliases
      state: link

  - name: clone zsh lazyload
    git:
      repo: https://github.com/qoomon/zsh-lazyload.git
      dest: ~/.local/share/aj-apps/zsh-lazyload

  - name: clone notes
    git:
      repo: git@github.com:alexjuda/notes-synced.git
      dest: ~/Documents/notes-synced
