- name: Set up a Fedora workstation.
  hosts: all

  tasks:

  - name: system tasks
    ansible.builtin.include_tasks:
      file: system-tools.yml

  - name: configs tasks
    ansible.builtin.include_tasks:
      file: link-configs.yml

  - name: gnome tasks
    ansible.builtin.include_tasks:
      file: gnome.yml

  - name: fonts tasks
    ansible.builtin.include_tasks:
      file: fonts.yml

  - name: python tasks
    ansible.builtin.include_tasks:
      file: python.yml

  - name: docker tasks
    ansible.builtin.include_tasks:
      file: docker.yml
