- name: Set up a Fedora workstation.
  hosts: all

  tasks:

  - name: print hello 1
    ansible.builtin.command: echo hello 1

  - name: include system tasks
    ansible.builtin.include_tasks:
      file: system-tools.yml
