- name: Set up a Fedora workstation.
  hosts: all

  tasks:

  - name: include system tasks
    ansible.builtin.include_tasks:
      file: system-tools.yml

  - name: include configs tasks
    ansible.builtin.include_tasks:
      file: link-configs.yml
