- name: clone pyenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.local/share/pyenv

- name: prep building native ext
  ansible.builtin.command:
    cmd: src/configure
    chdir: ~/.local/share/pyenv
    creates: ~/.local/share/src/Makefile

- name: build native ext
  ansible.builtin.command:
    cmd: make -C src
    chdir: ~/.local/share/pyenv
    creates: ~/.local/share/libexec/pyenv-realpath.dylib

- name: link pyenv lazyload script
  ansible.builtin.file:
    src: ~/Code/dotfiles/macos/pyenv.sh
    dest: ~/.local/share/aj-apps/pyenv.sh
    state: link

- name: install python system deps
  ansible.builtin.dnf:
    name:
      - bzip2
      - bzip2-devel
      - gcc
      - gdbm-libs
      - libffi-devel
      - libnsl2
      - libuuid-devel
      - make
      - openssl-devel
      - patch
      - readline-devel
      - sqlite
      - sqlite-devel
      - tk-devel
      - xz-devel
      - zlib-devel
    state: present
  become: true
  tags: superuser

- name: install latest Python 3
  ansible.builtin.command:
    cmd: ~/.local/share/pyenv/bin/pyenv install -k 3
