- name: install python system deps
  ansible.builtin.dnf:
    name:
      - bzip2
      - bzip2-devel
      - gcc
      - gdbm-libs
      - libffi-devel
      - libnsl2
      - libuuid-devel
      - make
      - openssl-devel
      - patch
      - readline-devel
      - sqlite
      - sqlite-devel
      - tk-devel
      - xz-devel
      - zlib-devel
    state: present
  become: true
  tags: superuser

- name: install cookiecutter
  community.general.pipx:
    name: cookiecutter

- name: install pyright
  community.general.pipx:
    name: pyright

- name: install pylsp
  community.general.pipx:
    name: "python-lsp-server[rope]"

- name: inject to pylsp
  community.general.pipx:
    name: "python-lsp-server"
    inject_packages:
      - python-lsp-black
      - python-lsp-ruff
      - pylsp-rope
    state: inject

- name: install ansible
  community.general.pipx:
    name: "ansible"
    # Includes executables of dependent packages.
    install_deps: true

- name: install watson
  community.general.pipx:
    name: "td-watson"
