- name: clone pyenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv

- name: prep building native ext
  ansible.builtin.command:
    cmd: src/configure
    chdir: ~/.pyenv
    creates: ~/.pyenv/src/Makefile

- name: build native ext
  ansible.builtin.command:
    cmd: make -C src
    chdir: ~/.pyenv
    creates: ~/.pyenv/libexec/pyenv-realpath.dylib

- name: link pyenv lazyload script
  ansible.builtin.file:
    src: ~/Code/dotfiles/macos/pyenv.sh
    dest: ~/.local/share/aj-apps/pyenv.sh
    state: link

- name: install python system deps
  ansible.builtin.dnf:
    name:
      - bzip2
      - bzip2-devel
      - gcc
      - gdbm-libs
      - libffi-devel
      - libnsl2
      - libuuid-devel
      - make
      - openssl-devel
      - patch
      - readline-devel
      - sqlite
      - sqlite-devel
      - tk-devel
      - xz-devel
      - zlib-devel
    state: present
  become: true
  tags: superuser

- name: install latest Python 3
  ansible.builtin.command:
    cmd: ~/.pyenv/bin/pyenv install -k 3.12.1
    creates: ~/.pyenv/versions/3.*

- name: install cookiecutter
  community.general.pipx:
    name: cookiecutter

- name: install pyright
  community.general.pipx:
    name: pyright

- name: install pylsp
  community.general.pipx:
    name: "python-lsp-server[rope]"

- name: inject to pylsp
  community.general.pipx:
    name: "python-lsp-server"
    inject_packages:
      - python-lsp-black
      - python-lsp-ruff
      - pylsp-rope
    state: inject
