---
# Running:
# ansible-playbook -i inventory.yml playbook.yml --extra-vars "git_email=<FIXME> git_username='<FIRST> <LAST>' -K"
# or:
# ansible-playbook -i inventory.yml playbook.yml --extra-vars "git_email=<FIXME> git_username='<FIRST> <LAST>'" --skip-tags superuser
- name: Set up a Fedora workstation.
  hosts: local

  tasks:
  - name: upgrade DNF packages
    dnf:
      name: "*"
      state: latest
    # requires '-K' flag when running
    become: true
    tags: superuser

  - name: Clone dotfiles
    git:
      repo: git@github.com:alexjuda/dotfiles.git
      dest: ~/Code/dotfiles
      clone: yes
      update: no

  - name: Set git email
    community.general.git_config:
      name: user.email
      scope: global
      value: "{{ git_email }}"

  - name: Set git username
    community.general.git_config:
      name: user.name
      scope: global
      value: "{{ git_username }}"

  - name: Link neovim config
    ansible.builtin.file:
      src: ~/Code/dotfiles/config/nvim
      dest: ~/.config/nvim
      state: link

  - name: install neovim
    dnf:
      name: "neovim"
      state: latest
    # requires '-K' flag when running
    become: true
    tags: superuser
