---
# Running:
# ansible-playbook -i inventory.yml playbook.yml --extra-vars "git_email=<FIXME> git_username='<FIRST> <LAST>'" --skip-tags superuser
# or:
# ansible-playbook -i inventory.yml playbook.yml --tags superuser -K
# or:
# ansible-playbook -i inventory.yml playbook.yml --extra-vars "@vars.yml" -K
- name: Set up a Fedora workstation.
  hosts: all

  tasks:

  - name: find URL for nerd font symbols
    ansible.builtin.command:
      cmd: ~/Code/dotfiles/scripts/fetch-gh-asset.py ryanoasis nerd-fonts NerdFontsSymbolsOnly.zip$ --first
    register: nerd_fonts_symbols_only_zip_url

  - name: unarchive nerd font symbols
    ansible.builtin.command:
      cmd: ~/Code/dotfiles/scripts/extract_from_zip.py "{{ nerd_fonts_symbols_only_zip_url }}" ~/.local/share/fonts --filename SymbolsNerdFont-Regular.ttf SymbolsNerdFontMono-Regular.ttf
      creates: ~/.local/share/fonts/SymbolsNerdFont*-Regular.ttf

  - name: reset font cache
    ansible.builtin.command: fc-cache ~/.local/share/fonts

  - name: add docker-ce DNF repo file
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/fedora/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: "644"
    become: true
    tags: superuser

  # Check out https://docs.docker.com/desktop/install/fedora/ to get the latest
  # RPM package link.

  - name: install docker desktop
    ansible.builtin.dnf:
      name: https://desktop.docker.com/linux/main/amd64/docker-desktop-4.26.1-x86_64.rpm
      state: present
      # The official Docker Desktop guide doesn't show how to validate GPG.
      disable_gpg_check: true
    become: true
    tags: superuser

  # Uncomment in development:
  # - name: wip
  #   ansible.builtin.command: df -h
