---
# Running:
# ansible-playbook -i inventory.yml playbook.yml --extra-vars "git_email=<FIXME> git_username='<FIRST> <LAST>'" --skip-tags superuser
# or:
# ansible-playbook -i inventory.yml playbook.yml --tags superuser -K
# or:
# ansible-playbook -i inventory.yml playbook.yml --extra-vars "@vars.yml" -K
- name: Set up a Fedora workstation.
  hosts: local

  tasks:
  - name: upgrade DNF packages
    dnf:
      name: "*"
      state: latest
    # requires '-K' flag when running
    become: true
    tags: superuser

  - name: clone dotfiles
    git:
      repo: git@github.com:alexjuda/dotfiles.git
      dest: ~/Code/dotfiles
      clone: yes
      update: no

  - name: Set git email
    community.general.git_config:
      name: user.email
      scope: global
      value: "{{ git_email }}"

  - name: Set git username
    community.general.git_config:
      name: user.name
      scope: global
      value: "{{ git_username }}"

  - name: clone paq
    git:
      repo: https://github.com/savq/paq-nvim.git
      dest: ~/.local/share/nvim/site/pack/paqs/start/paq-nvim

        # Please run: nvim -c ":PaqSync" manually

  - name: make ltex dict dir
    ansible.builtin.file:
      path: ~/.local/share/lang-servers/ltex-ls-data
      state: directory

  - name: touch ltex dict file
    ansible.builtin.file:
      path: ~/.local/share/lang-servers/ltex-ls-data/dict.txt
      state: touch

  - name: link neovim config
    ansible.builtin.file:
      src: ~/Code/dotfiles/config/nvim
      dest: ~/.config/nvim
      state: link

  - name: link kitty config
    ansible.builtin.file:
      src: ~/Code/dotfiles/config/kitty
      dest: ~/.config/kitty
      state: link

  - name: enable lazygit's copr
    community.general.copr:
      name: atim/lazygit
    # requires '-K' flag when running
    become: true
    tags: superuser

  - name: install system packages
    ansible.builtin.dnf:
      name:
        - fd-find
        - gcc-c++
        - gh
        - glances
        - htop
        - kitty
        - lazygit
        - neovim
        - ripgrep
        - zsh
      state: latest
    # requires '-K' flag when running
    become: true
    tags: superuser

  - name: install GUI apps
    community.general.flatpak:
      name:
        - com.spotify.Client
        - org.signal.Signal
    # requires '-K' flag when running
    become: true
    tags: superuser

  - name: swap caps lock<->esc & right cmd<->ctrl
    community.general.dconf:
      key: "/org/gnome/desktop/input-sources/xkb-options"
      value: "['caps:swapescape', 'ctrl:swap_rwin_rctl']"

  - name: set zsh as the default shell for user {{ ansible_user_id }}
    vars:
      the_user: "{{ ansible_user_id }}"
    ansible.builtin.user:
      name: "{{ the_user }}"
      shell: /bin/zsh
    become: true
    tags: superuser

  - name: link zsh config
    ansible.builtin.file:
      src: ~/Code/dotfiles/macos/.zshrc
      dest: ~/.zshrc
      state: link

  - name: link aliases
    ansible.builtin.file:
      src: ~/Code/dotfiles/linux/.bash_aliases
      dest: ~/.bash_aliases
      state: link

  - name: clone zsh lazyload
    git:
      repo: https://github.com/qoomon/zsh-lazyload.git
      dest: ~/.local/share/aj-apps/zsh-lazyload

  - name: find URL for nerd font symbols
    ansible.builtin.command:
      cmd: ~/Code/dotfiles/scripts/fetch-gh-asset.py ryanoasis nerd-fonts NerdFontsSymbolsOnly.zip$ --first
    register: nerd_fonts_symbols_only_zip_url

  - name: unarchive nerd font symbols
    ansible.builtin.command:
      cmd: ~/Code/dotfiles/scripts/extract_from_zip.py "{{ nerd_fonts_symbols_only_zip_url }}" ~/.local/share/fonts --filename SymbolsNerdFont-Regular.ttf SymbolsNerdFontMono-Regular.ttf
      creates: ~/.local/share/fonts/SymbolsNerdFont*-Regular.ttf

  - name: reset font cache
    ansible.builtin.command: fc-cache ~/.local/share/fonts
