" Generated by vim-plug
" sob, 1 maj 2021, 11:36:39
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['colorbuddy.vim'].commit = '87c80e3f4a590d0387d9b128d1f1fc456759408a'
silent! let g:plugs['completion-nvim'].commit = '8bca7aca91c947031a8f14b038459e35e1755d90'
silent! let g:plugs['fzf'].commit = '4cd621e877cb3a8e44b12ba3a7ce58709862922f'
silent! let g:plugs['fzf.vim'].commit = '75c7e87de1ed7ff41183d479b1a23023070bfe54'
silent! let g:plugs['markdown-preview.nvim'].commit = 'e5bfe9b89dc9c2fbd24ed0f0596c85fd0568b143'
silent! let g:plugs['nerdtree'].commit = '81f3eaba295b3fceb2d032db57e5eae99ae480f8'
silent! let g:plugs['nvim-lspconfig'].commit = '62977b6b2eeb20bd37703ebe4bc4b4c2ef006db2'
silent! let g:plugs['nvim-lspfuzzy'].commit = '0e369ae5a1230c4867663c2c8cc441f728ae0a5b'
silent! let g:plugs['nvim-treesitter'].commit = '2873d1efdaedf562af202d13594f1022def1fa49'
silent! let g:plugs['onebuddy'].commit = '7e16006e7dde15e3cb72889f736c49409db6ff42'
silent! let g:plugs['vim-commentary'].commit = '349340debb34f6302931f0eb7139b2c11dfdf427'
silent! let g:plugs['vim-markdown'].commit = '9d87cc19179496db50fb6d902987737c4b522e38'
silent! let g:plugs['vim-rooter'].commit = '662c00676abab9d7ce16bf9f202420bf86cc6554'
silent! let g:plugs['vim-sandwich'].commit = '9e6340affe9f53c11a6975a5f50b9bf48adb692c'
silent! let g:plugs['vim-which-key'].commit = '20163f6ffda855fa40a11cb999002211dc66288f'

PlugUpdate!

